#!/usr/bin/env bash
#
# Auto-bump `archon_sha` in `Youbiquity-00001-Backup/youbiquity-archon-infra`
# and open (or update) a PR proposing the bump. Pushing to Archon `main`
# does NOT deploy on its own — merging the PR this opens is what fires
# the infra `deploy.yml`. The PR title/body make that explicit.
#
# Called by:
#   - `.husky/pre-push` — runs in the same process as `git push`, so the
#     PR URL prints to the user's stdout (and to the Claude session
#     transcript) immediately after the push completes.
#   - `.github/workflows/auto-bump-infra.yml` — backstop that catches
#     `git push --no-verify` and direct web-UI merges.
#
# Idempotent. Same SHA → same branch (`auto/bump-archon-<short>`) → the
# script `--force-with-lease`s instead of stacking PRs. If a stale bump
# PR exists for an OLDER SHA, this script closes it first so the
# operator never has to choose between two open auto-bumps.
#
# Failure mode: never blocks the push. If the GH token can't be
# resolved or the API call fails, the script prints a warning to stderr
# and exits 0. Only the push to Archon matters; the bump is opportunistic.
#
# Usage: scripts/auto-bump-infra.sh <archon-sha-to-pin>
set -euo pipefail

ARCHON_SHA="${1:-}"
if [ -z "$ARCHON_SHA" ]; then
  echo "auto-bump-infra: no SHA provided, skipping" >&2
  exit 0
fi

INFRA_REPO="${INFRA_REPO:-Youbiquity-00001-Backup/youbiquity-archon-infra}"
INFRA_OWNER="${INFRA_REPO%%/*}"
SHORT="${ARCHON_SHA:0:7}"
BRANCH="auto/bump-archon-${SHORT}"

# ---- Resolve a GH token. Order is most-specific-source-wins so that a
# stale ambient $GITHUB_TOKEN in a sandbox doesn't shadow a per-org
# token that actually has access to the infra repo:
#   1. $INFRA_BUMP_TOKEN — explicit override (CI sets this from secrets).
#   2. /tmp/gh-tokens — Claude sandbox credential helper file (per-org
#      lookup; tab-separated owner→token; cred-helper at
#      /tmp/gh-credential-helper.sh). Only present in sandboxes.
#   3. `gh auth token` — local dev with gh CLI installed.
#   4. $GH_TOKEN / $GITHUB_TOKEN — last-resort env-bag fallbacks.
TOKEN=""
if [ -n "${INFRA_BUMP_TOKEN:-}" ]; then
  TOKEN="$INFRA_BUMP_TOKEN"
elif [ -f /tmp/gh-tokens ]; then
  OWNER_LC=$(printf '%s' "$INFRA_OWNER" | tr '[:upper:]' '[:lower:]')
  TOKEN=$(awk -F '\t' -v o="$OWNER_LC" '$1==o{print $2; exit}' /tmp/gh-tokens || true)
fi
if [ -z "$TOKEN" ] && command -v gh >/dev/null 2>&1; then
  TOKEN="$(gh auth token 2>/dev/null || true)"
fi
if [ -z "$TOKEN" ] && [ -n "${GH_TOKEN:-}" ]; then
  TOKEN="$GH_TOKEN"
fi
if [ -z "$TOKEN" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
  TOKEN="$GITHUB_TOKEN"
fi

if [ -z "$TOKEN" ]; then
  cat >&2 <<EOF

  ⚠️  auto-bump-infra: no GitHub token found — skipping the infra PR.
     Push to Archon will still complete, but you'll need to bump
     archon_sha in ${INFRA_REPO} manually for this SHA to deploy.
     Set INFRA_BUMP_TOKEN=<PAT with repo scope on the infra repo>
     or run \`gh auth login\` to enable.

EOF
  exit 0
fi

# ---- Clone or refresh the infra repo into a per-script tmpdir. Reuse
#      between calls in the same shell session so back-to-back pushes
#      don't re-download a fresh tree.
WORKDIR="${TMPDIR:-/tmp}/auto-bump-infra-checkout"
REPO_URL="https://x-access-token:${TOKEN}@github.com/${INFRA_REPO}.git"
if [ -d "$WORKDIR/.git" ]; then
  git -C "$WORKDIR" remote set-url origin "$REPO_URL" >/dev/null
  git -C "$WORKDIR" fetch --quiet origin main
  git -C "$WORKDIR" checkout --quiet main
  git -C "$WORKDIR" reset --hard --quiet origin/main
else
  rm -rf "$WORKDIR"
  git clone --quiet --depth=1 "$REPO_URL" "$WORKDIR"
fi

# ---- Bail early if already pinned to this SHA.
TFVARS="$WORKDIR/versions.tfvars"
if grep -Fxq "archon_sha = \"${ARCHON_SHA}\"" "$TFVARS"; then
  echo "auto-bump-infra: ${INFRA_REPO} already pins archon_sha=${SHORT}, nothing to do"
  exit 0
fi

# ---- Edit versions.tfvars in-place. awk + mv is portable across
#      GNU/BSD sed quirks.
TMP="$TFVARS.tmp"
awk -v sha="$ARCHON_SHA" '
  /^archon_sha = / { print "archon_sha = \"" sha "\""; next }
  { print }
' "$TFVARS" > "$TMP"
mv "$TMP" "$TFVARS"

# ---- Commit + push branch. --force-with-lease=ref: matches whether
#      the remote ref is absent OR matches our local view; safer than
#      bare --force on a long-lived auto branch.
git -C "$WORKDIR" checkout --quiet -B "$BRANCH"
git -C "$WORKDIR" \
  -c user.email='archon-bot@noreply.youbiquity.com' \
  -c user.name='archon-auto-bump' \
  commit -aqm "deploy: bump archon to ${SHORT}" \
         -m "Auto-generated by Archon's pre-push hook (or auto-bump-infra.yml CI backstop). Merge to deploy this SHA to dev."
git -C "$WORKDIR" push --force --quiet --set-upstream origin "$BRANCH"

# ---- GH API helper. Authorization in the header (not the URL) so
#      curl error output never leaks the token.
api() {
  local method="$1" path="$2" body="${3:-}"
  if [ -n "$body" ]; then
    curl -fsS -X "$method" \
      -H "Authorization: Bearer ${TOKEN}" \
      -H "Accept: application/vnd.github+json" \
      -d "$body" \
      "https://api.github.com${path}"
  else
    curl -fsS -X "$method" \
      -H "Authorization: Bearer ${TOKEN}" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com${path}"
  fi
}

# ---- Find existing PR for this branch (idempotent re-run) or open one.
EXISTING=$(api GET "/repos/${INFRA_REPO}/pulls?head=${INFRA_OWNER}:${BRANCH}&state=open" \
  | python3 -c 'import sys,json; prs=json.load(sys.stdin); print(prs[0]["html_url"] if prs else "")')

if [ -z "$EXISTING" ]; then
  PR_PAYLOAD=$(python3 -c '
import json, sys
title = sys.argv[1]
head  = sys.argv[2]
sha   = sys.argv[3]
short = sha[:7]
body  = (
    f"Bumps `archon_sha` to `{sha}` (`{short}`).\n\n"
    f"**Merge to deploy to dev.**\n\n"
    f"Auto-generated by the Archon `pre-push` hook (or the `auto-bump-infra.yml` CI backstop).\n\n"
    f"- Pushing to Archon `main` does *not* deploy on its own — merging this PR is what fires the existing infra `deploy.yml`.\n"
    f"- Prod is **not** auto-bumped. For prod, use `gh workflow run deploy.yml -f environment=prod` against the same SHA after this lands.\n"
)
print(json.dumps({"title": title, "head": head, "base": "main", "body": body}))
' "deploy: bump archon to ${SHORT}" "$BRANCH" "$ARCHON_SHA")
  PR_URL=$(api POST "/repos/${INFRA_REPO}/pulls" "$PR_PAYLOAD" \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["html_url"])')
  ACTION="opened"
else
  PR_URL="$EXISTING"
  ACTION="updated (already open)"
fi

# ---- Close older auto-bump PRs targeting different SHAs, so a stack
#      of unmerged bumps doesn't accumulate.
OTHERS=$(api GET "/repos/${INFRA_REPO}/pulls?state=open&base=main&per_page=100" \
  | python3 -c '
import sys, json
keep = sys.argv[1]
for pr in json.load(sys.stdin):
    head = pr.get("head", {}).get("ref", "")
    if head.startswith("auto/bump-archon-") and head != keep:
        num = pr["number"]
        print(f"{num}\t{head}")
' "$BRANCH")
if [ -n "$OTHERS" ]; then
  while IFS=$'\t' read -r num head; do
    api PATCH "/repos/${INFRA_REPO}/pulls/${num}" '{"state":"closed"}' >/dev/null
    echo "  - closed superseded auto-bump PR #${num} (${head})"
  done <<< "$OTHERS"
fi

# ---- Loud, copy-pasteable final message. Survives the noisy git push
#      output and lands at the bottom of any session transcript.
cat <<EOF

  ✓ auto-bump-infra: ${ACTION} PR for archon_sha=${SHORT} (dev)
    → ${PR_URL}
    Merge it for the change to actually ship to dev.
    Prod stays manual: \`gh workflow run deploy.yml -f environment=prod\`.

EOF
